### ISSUE TITLE
Plugin does not expose types

### ISSUE THREAD

**Issue by kmai** [maumercado/fastify-jaeger#4]
When using the plugin with Typescript, types are not available.

Types aren't published on DefinitelyTyped either.

Workarounds to type the `jaeger()` API often break projects and should follow best practices as per [documentation](https://www.fastify.io/docs/v1.14.x/TypeScript/#authoring-plugin-types)

**Comment by maumercado** [comment]
Feel free to send a PR with the types :)

**Comment by joylazari** [comment]
Please take a look at PR #7
